### ISSUE TITLE
docker run has errors on MAC OS

### ISSUE THREAD

**Issue by minnieshi** [databricks/containers#114]
it does not seem to support mac os

`$ docker run databricksruntime/standard

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
$`

`Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
`

**Comment by alecglen** [comment]
Duplicate of https://github.com/databricks/containers/issues/99

**Comment by xinzhao-db** [comment]
close duplicate
