### ISSUE TITLE
The README Azure link gives: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by marcindulak** [databricks/containers#147]
The [Azure](https://docs.azuredatabricks.net/user-guide/clusters/custom-containers.html) link at https://github.com/databricks/containers/blob/master/README.md gives

> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

![Screenshot from 2023-11-14 18-30-02](https://github.com/databricks/containers/assets/3178318/1bc78aba-495e-4032-9c8f-18a882cc25ab)

**Comment by xinzhao-db** [comment]
merged.
