### ISSUE TITLE
Databricks Runtime 15.0-LTS

### ISSUE THREAD

**Issue by MichaelisTrofficus** [databricks/containers#186]
Hi!

When are you releasing the 15.0-LTS Standard runtime version? Because it seems it's out of beta release right?

Thanks!

**Comment by lmsxyz** [comment]
I guess Databricks Connect needs to be upgraded also, but not quite there yet? https://pypi.org/project/databricks-connect/14.3.1/

**Comment by xinzhao-db** [comment]
There is no 15.0-LTS because 15.0 is not an LTS version. We only ship one LTS version per DBR major version, for DBR 15, the LTS version is 15.4 and DCS 15.4 is released.
