### ISSUE TITLE
Databricks Runtime 15.4-LTS

### ISSUE THREAD

**Issue by omerzamir** [databricks/containers#196]
Now that DBR 15.4-LTS is [released](https://docs.databricks.com/en/release-notes/runtime/15.4lts.html) a Docker image is missing in docker hub.

Do you plan to release an image for this version?

**Comment by omerzamir** [comment]
@xinzhao-db any chance for update here?

**Comment by omerzamir** [comment]
I see a new 15.4 image is released, closing the issue

**Comment by NicholasFiorentini** [comment]
For those using this in prod, please note that https://github.com/databricks/containers/issues/201.
