### ISSUE TITLE
How to prevent my python module being override by Databricks runtime?

### ISSUE THREAD

**Issue by jerrychenhf** [databricks/containers#29]
I am try to use my own version of scikit-learn by providing my custom docker image. 
But I found from the release notes that Databricks runtime also includes scikit-learn module by default (for example Databricks runtime 7.1) 

Will databricks runtime override my scikit-learn version when building the final image for docker container? If yes, is there a way to prevent it?

Thanks,
Haifeng

**Comment by mengxr** [comment]
No. If you use your own container, the Python layer from Databricks Runtime is not used.
