### ISSUE TITLE
Runtime 7.x image updates

### ISSUE THREAD

**Issue by aryah55** [databricks/containers#33]
My first question is. When will you update your Docker images to be run time 7.x? 

I will need this very soon as I have to provide an image for double digit streams of work and need cluster start times to be optimal as Init scripts are not viable for so many packages that I need to install. We do not want the administration over head of maintaining custom init scripts for each stream of work and 20 minute cluster start times. with ACR image it is within 5 minutes

My other question is that do you have comprehensive documentation anywhere on using another tool as good as ganglia and how to configure it in detail for Azure Databricks Clusters since in current images it is not supported and you plan to remove support for it in the near future?

Thanks
A

**Comment by thompdre84** [comment]
If you look under Pull Requests, someone has made a Runtime 7 Dockerfile that is working for me.

**Comment by aryah55** [comment]
Thanks
