### ISSUE TITLE
Internal error message: Spark failed to start: Timed out after 60 seconds

### ISSUE THREAD

**Issue by thompdre84** [databricks/containers#38]
I created a custom docker image that contains Opencv 4, LightGBM, Torch, and a few other libraries compiled for CUDA on a g4dn.xlarge ec2 instance. The image is 17.1GB according docker image ls.
I am getting the following error message when starting a g4dn.xlarge cluster:`Internal error message: Spark failed to start: Timed out after 60 seconds`
This error does not occur if the image runs in a g4dn.2xlarge. There are no init scripts being used. Is there a Spark config or something else that needs to be set to use a g4dn.xlarge cluster without getting a timeout?

Runtime(s): 7.2 (error), 7.3 LTS (error)

**Comment by evanye** [comment]
@thompdre84 is this still happening? I believe the timeout has been increased to 90 seconds for cpu clusters and 120 seconds for gpu clusters for everyone

**Comment by thompdre84** [comment]
I believe the actual issue ended up being that it couldn't find GPU spot clusters for the workers, at least not in the amount of time. Switching to all on-demand instances seemed to remedy the issue at the time. I haven't seen any issues in a few months but it if comes up again I will open a new issue. I believe this was around the time it was difficult at certain times to find any available g4dn.xlarge instances in us-west-2. It seems AWS has added more capacity. I'll open a new issue if it pops up again.
