### ISSUE TITLE
Ubuntu 16.04 EoL

### ISSUE THREAD

**Issue by ViaFerrata** [databricks/containers#46]
Hi there,

since Ubuntu 16.04 is EoL in April, do you intend to offer Ubuntu 18.04 versions of the dockerfiles?
Of course you could switch the apt-get commands to the ```old-releases.ubuntu.com``` source, but the file would still need to be changed.

For my project, I tried to combine the experimental ```ubuntu18.04-minimal``` image with the ```ubuntu/python``` one by just changing the FROM command from 16.04 to 18.04.
Seems like it works, I could use the docker image as normal in a DB cluster, and I could also import code in a notebook from a python package that has been installed to the dcs-minimal conda env in the docker container.

But of course that's not a sophisticated test case.

**EDIT:**
Sorry, have to correct myself. 
The change from 16.04 -> 18.04 works, but through painful debugging I realized that installing the ```sphinx-autoapi``` package into the conda environment leads to a failure in a ```conda list``` command.
Probably related to [this conda issue](https://github.com/conda/conda/issues/9104), since it's exactly the same error.

The following packages are dependencies of the ```sphinx-autoapi``` package:
```urllib3, pyparsing, MarkupSafe, idna, chardet, wrapt, typed-ast, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, requests, packaging, lazy-object-proxy, Jinja2, imagesize, docutils, babel, alabaster, unidecode, sphinx, PyYAML, astroid```

**Is it safe to upgrade the conda in the docker image, in order to get the conda bugfix in 4.7.12, or does this lead to problems (you probably chose this particular conda version on purpose)?**

**EDIT2**
I can confirm that upgrading conda to 4.7.12 fixed the error, and my python package used via db notebook still works.

**Comment by evanye** [comment]
Can you check if #49 addresses the ubuntu 16 eol concerns? If so, can you update the ticket to make it focus on the conda issues?

**Comment by ViaFerrata** [comment]
Yep, that fixes it, I've already used this solution for a few months.

In order to not make this issue too confusing, I'll split the conda problem to a new issue.
