### ISSUE TITLE
Stable Databricks Docker Container Significantly Behind Current DBR version.

### ISSUE THREAD

**Issue by ttelfer** [databricks/containers#48]
Currently the stable databricks docker container is significantly behind the stable DBR (8.x at the time of writing). The experimental containers are 7.x. Will these containers be kept more up to date?

**Comment by evanye** [comment]
@ttelfer I just pushed updated base images for 7.x yesterday. Please try them out!

**Comment by iantheparker** [comment]
Is 8.x on the way too?

**Comment by evanye** [comment]
@iantheparker If I had to guess, the 7.x base images would also work for the 8.x databricks runtimes as well. Here are the 8.x dependencies: https://docs.databricks.com/release-notes/runtime/8.3.html#system-environment
