### ISSUE TITLE
is there a rapids container?

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [databricks/containers#55]
I am trying the container below but I am getting an error indicating it is not found. Am I missing something? Thanks
https://github.com/databricks/containers/blob/74fbb7fba92e9dc1bf69a7242d58b86661101b03/ubuntu/gpu/cuda-11/build.sh#L9

**Comment by evanye** [comment]
I think @lu-wang-dl readded this recently https://github.com/databricks/containers/pull/77
