### ISSUE TITLE
Ubuntu Docker Image Vulnerabilities

### ISSUE THREAD

**Issue by a-guy-on-the-internet** [databricks/containers#76]
Hello, I'm not sure if this is where I should put this, but there are 4 vulnerabilities for the underlying 18.04 ubuntu image or at least those 4 are getting flagged by our scanning tool. Could we get those resolved by probably just running an update on the images?

https://ubuntu.com/security/notices/USN-5189-1
https://ubuntu.com/security/notices/USN-5168-1
https://ubuntu.com/security/notices/USN-5133-1
https://launchpad.net/ubuntu/+source/python3.7/3.7.5-2~18.04.4

**Comment by evanye** [comment]
Yes, you can get it resolved by running something like `apt-get update` inside your base image before publishing to your internal repo. This is what we do for our non DCS images.
