### ISSUE TITLE
unbuntu version

### ISSUE THREAD

**Issue by US579** [databricks/containers#80]
is there any plan to support ubuntu 20.04?

**Comment by evanye** [comment]
https://github.com/databricks/containers/pull/81

**Comment by US579** [comment]
> 

thanks for the link, but this change is for the databricksruntime/minimal do we have databricksruntime/dbfsfuse upgraded already?

**Comment by evanye** [comment]
@US579 the other images are built off of minimal, so it is reflected in the PR. dbfsfuse is reflected here: https://github.com/databricks/containers/pull/81/files#diff-8980645af3a18b83c3eb1ac52bcb9dabfa48c0967895d2e6fd2a5143cd01e3b5L1

That being said, you would need to rebuild images from Dockerfile to use it right now. We will have the images in dockerhub updated shortly and when that happens, you can build off of dockerhub directly.
cc @alexjinghn
